apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aliyun-vector-add
spec:
  template:
    metadata:
      labels:
        app: aliyun-vector-add
      annotations:
        k8s.aliyun.com/eci-use-specs: ecs.gn5i-c4g1.xlarge  # Specify a GPU-accelerated ECS instance type that is supported by Knative. 
    spec:
      containers:
        - image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
          ports:
          - containerPort: 8080
          resources:
            limits:
              nvidia.com/gpu: '1'    # Specify the number of GPUs that are required by the container. This field is required. If you do not specify this field, an error is returned when the pod is launched. 