apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dcgmproftester-knative-gpu
spec:
  template:
    spec:
      containers:
      - image: nvidia/samples:dcgmproftester-2.0.10-cuda11.0-ubuntu18.04
        args: ["--no-dcgm-validation", "-t 1004", "-d 30"]  
        resources:
          limits:
            nvidia.com/gpu: 1